In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
l = range(100)
%timeit [i**2 for i in l]

6.18 µs ± 371 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [4]:
a = np.arange(100)
%timeit a**2

586 ns ± 41.6 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# Creating Array

In [5]:
a = np.array([1,2,3,4]) # one dimensional array
print(a.ndim)

1


In [6]:
b = np.array([[1,2,3],[4,5,6]]) # two dimensional array
print(b.ndim)

2


In [7]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) # multi dimensional array
print(c.ndim)
print(c)

3
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
print(a.shape) #vector

(4,)


In [9]:
print(b.shape) # matrix

(2, 3)


In [10]:
print(c.shape) # cube

(2, 2, 2)


# Function creating array

In [11]:
a = np.array(10) 
print(a)

10


In [12]:
a = np.arange(1,10,2) 
print(a)

[1 3 5 7 9]


In [13]:
#using linspace
a = np.linspace(0,1,5)
print(a)

[0.   0.25 0.5  0.75 1.  ]


In [14]:
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
a = np.eye(3,3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
a = np.diag([1,2,3,4])
print(a)


[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [19]:
print(np.diag(a))

[1 2 3 4]


# Basic Datatypes

In [20]:
a = np.arange(10)
print(a.dtype)

int32


In [21]:
a = np.arange(10,dtype="float")
print(a.dtype)

float64


In [22]:
a = np.zeros((3,3))
print(a)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


# other datatypes

In [23]:
a = np.array([1+2j,2+4j])
print(a.dtype)

complex128


In [24]:
a = np.array([True,False])
print(a.dtype)

bool


In [25]:
a = np.array(["vamsi","computer"])
print(a.dtype) #unicode string type

<U8


# Indexing and slicing

In [26]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [27]:
a = np.arange(10)
print(a[5])

5


In [28]:
a = np.diag([1,2,3])
print(a)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [29]:
a = np.diag([1,2,3])
print(a[2,2])

3


In [30]:
a[2,1] = 5
print(a)

[[1 0 0]
 [0 2 0]
 [0 5 3]]


# slicing

In [31]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [32]:
print(a[1:8:2])

[1 3 5 7]


In [33]:
a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [34]:
a = np.arange(10)
a[5:8] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10,  8,  9])

# coping and Viewing

In [35]:
a = np.arange(10)
b = a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [36]:
a = np.arange(10)
b = a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [37]:
a = np.arange(10)
b = a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [38]:
b[0] = 10
print(a)
print(b) # to confirm share memory

[10  1  2  3  4  5  6  7  8  9]
[10  2  4  6  8]


In [39]:
a = np.arange(10)
b = a[::2].copy() #force a copy
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [40]:
a = np.arange(10)
b = a[::2].copy() #force a copy
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [41]:
print(np.shares_memory(a,b))

False


In [42]:
b[0] = 10
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[10  2  4  6  8]
